@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.minecraftabnormals.savageandravage.common.entity.goals;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;