package com.farcr.savageandravage.common.entity;

import com.farcr.savageandravage.core.registry.SREntities;

import net.minecraft.entity.AreaEffectCloudEntity;
import net.minecraft.entity.EntityType;
import net.minecraft.entity.projectile.ThrowableEntity;
import net.minecraft.util.math.RayTraceResult;
import net.minecraft.world.World;

public class CreeperSporeCloudEntity extends ThrowableEntity {
    public CreeperSporeCloudEntity(EntityType<? extends CreeperSporeCloudEntity> type, World worldIn){
        super(type, worldIn);

    }

    @Override
    protected void onImpact(RayTraceResult result) {

    }
    
    @Override
    protected void registerData() {
        //autogenerated, something will be here soon
    }
//something will be here soon
}
