package com.farcr.savageandravage.common.entity;

import com.farcr.savageandravage.core.registry.SREntities;

import net.minecraft.entity.AreaEffectCloudEntity;
import net.minecraft.entity.EntityType;
import net.minecraft.entity.projectile.ThrowableEntity;
import net.minecraft.util.math.RayTraceResult;
import net.minecraft.world.World;

public class CreeperSporeCloudEntity extends ThrowableEntity {
    public CreeperSporeCloudEntity(EntityType<? extends CreeperSporeCloudEntity> type, World worldIn){
        super(type, worldIn);

    }

    @Override
    protected void onImpact(RayTraceResult result) {
        //this.summonCreepies(); soon
    }
    
    //soon
   /* public void summonCreepies() 
    {
      CreepieEntity creepie = SREntities.CREEPIE.get().create(world);
      AreaEffectCloudEntity areaeffectcloudentity = new AreaEffectCloudEntity(world, getPosition().getX(),getPosition().getY(), getPosition().getZ());
      creepie.setLocationAndAngles(creepie.getPosX(), creepie.getPosY(), creepie.getPosZ(), creepie.getYaw(prevRotationYaw), creepie.getPitch(prevRotationPitch));
      this.world.addEntity(creepie);
    } */

    @Override
    protected void registerData() {
        //autogenerated, something will be here soon
    }
//something will be here soon
}
