@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.minecraftabnormals.savageandravage.client.model;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;