@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.minecraftabnormals.savageandravage.common.entity;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;