@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.minecraftabnormals.savageandravage.common.effect;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;